const ideas = [
  'Use a laser pointer for interactive play with unpredictable movements',
  'Create multi-level cardboard structures for exploration and rest',
  'Provide rustling paper bags for hiding and exploration',
  'Roll lightweight balls (like ping pong balls or pom-poms) for batting and chasing',
  'Install a secure window perch for outdoor observation',
  'Use ribbons or strings for zigzag motions to trigger chasing instincts',
  'Offer interactive puzzle toys and feeders for mental stimulation and treat-finding',
  'Provide catnip-infused toys for scent-based excitement',
  'Use feather wands to mimic bird movements and engage hunting instincts',
  'Hide treats or kibble around the house for foraging and scent tracking',
  'Set up various scratching posts with attractive scents',
  'Use pet-safe bubbles for chasing play',
  'Implement clicker training for teaching tricks',
  'Create agility courses using household items',
  'Rotate toys regularly to maintain novelty',
  'Toss lightweight, crunchy paper balls for batting and chasing',
  'Provide plush companions for kicking and playful wrestling',
  'Offer multi-level structures for climbing, exercise, and observation',
  'Create tunnel-like toys from paper towel rolls for exploration',
  'Make a DIY kicker toy using socks stuffed with paper',
  'Engage in supervised, gentle tug of war with string toys',
  'Provide secure aquarium viewing opportunities for visual stimulation',
  'Attach jingle bells to strings for engaging auditory play',
  'Roll small toy vehicles to trigger chasing and pouncing instincts',
  'Craft a homemade cardboard scratching surface',
  'Provide a ball-in-track toy for independent batting entertainment',
  'Play videos of birds and small animals for feline entertainment',
  'Use reflective surfaces to create intriguing, chaseable light patterns',
  'Provide electronic toys with unpredictable movements',
  'Guide cats through obstacle courses',
  'Dispense treats from adjustable difficulty balls',
  'Infuse small toy balls with catnip or silvervine scent',
  'Hang toys from door frames with elastic for bouncy movements',
  'Install a tall post combining climbing, scratching, and elevated resting spots',
  'Scatter kibble in textured mats to simulate natural foraging',
  'Offer various textured surfaces for paw exploration and sensory enrichment',
  'Encourage supervised playtime with other cats or human family members',
  'Create enticing paths throughout the home using catnip or treats',
  'Teach cats to weave through homemade agility ladders for rewards',
  'Use positive reinforcement for trick training',
  'Set up supervised playdates with compatible feline friends',
  'Play the "shell game" with treats hidden under cups',
  'Create a sensory mat with different textures (fur, foil, bubble wrap)',
  'Grow cat-safe herbs for sensory enrichment',
  'Play nature sounds or cat-specific music',
  'Change the location of cat trees or tunnels periodically',
  'Play "fetch" with small, lightweight balls or toy mice',
  'Rearrange furniture to create new pathways and hiding spots',
  'Create a "catio" or secure outdoor enclosure for supervised exploration',
  'Create a DIY cat hammock using an old t-shirt and sturdy cardboard',
  'Make a treat-dispensing piñata using a small cardboard box',
  'Set up a cat-safe herb garden with cat grass, catnip, and valerian',
  'Create a "fish pond" using a shallow tray with floating toys',
  'Make a DIY cat treadmill using a large cardboard tube',
  'Set up a "kitty TV" with a bird feeder visible from a window',
  'Create a vertical climbing wall with sisal-wrapped poles',
  'Make a cat-friendly ball pit using a shallow box and plastic balls',
  'Design a "snuffle mat" for foraging using strips of fleece',
  'Create a "cat chariot" by attaching a small basket to a remote-controlled car',
  'Set up a "catwalk" using sturdy shelves along the walls',
  'Make a DIY wobble toy using a weighted bottom and feathers on top',
  'Create a "mini golf" course for your cat using cups and small balls',
  'Design a "follow the treat" game using a long, clear tube',
  'Make a "kitty seesaw" using a plank and a stable cylinder',
  'Create a "bubble wrap runway" for textural enrichment',
  'Set up a "treat treasure hunt" in a kiddie pool filled with ball pit balls',
  'Design a "feline forage board" using a muffin tin and balls',
  'Create a "cat-friendly xylophone" using hanging tubes of different lengths',
  'Make a "feather forest" using dowels and feathers in a stable base',
  'Set up a "scent station" with different safe essential oils on cotton balls',
  'Create a "caterpillar chaser" using a motorized, worm-like toy',
  'Design a "feline fun house" with mirrors and different textures',
  'Make a "kitty kerplunk" game using a clear container and straws',
  'Create a "cat-friendly wind chime" with dangling, lightweight objects',
  'Set up a "lunar landscape" play area with craters and tunnels',
  'Design a "feline fishing game" with magnetic toys in a shallow water bowl',
  'Create a "cat parkour course" using sturdy cardboard structures',
  'Make a "treat tornado" toy using a clear plastic bottle and holes',
  'Set up a "kitty ball run" using PVC pipes and joints',
  'Create a "cat-friendly sensory bin" with various safe materials',
  'Design a "feline photo booth" with cat-sized props and backdrops',
  'Make a "cat-friendly abacus" with sliding treats on dowels',
  'Create a "kitty car wash" using hanging strips of fabric',
  'Set up a "treat-dispensing pendulum" for interactive play',
  'Design a "feline ASMR station" with different textured surfaces',
  'Create a "cat-friendly zen garden" with fine sand and small objects',
  'Make a "kitty conveyor belt" using a treadmill-like cardboard structure',
  'Set up a "paw painting station" with non-toxic, pet-safe paints',
  'Design a "feline forensics game" hiding treats with different scents',
  'Create a "cat-friendly ball launcher" using a cardboard tube and elastic',
  'Make a "kitty cube puzzle" with treats hidden in interconnected boxes',
  'Set up a "feline fashion show runway" with different floor textures',
  'Design a "cat-friendly whack-a-mole game" using a box and holes',
  'Create a "kitty crush game" using treats behind a clear, sturdy screen',
  'Make a "feline ring toss" game using toilet paper rolls and rope rings',
  'Set up a "cat-friendly shadow puppet theater" with a light and screen',
  'Design a "kitty carnival" with various DIY games and activities',
  'Create a "feline mission impossible course" with yarn creating a laser-like maze',
  'Make a "cat-friendly silent disco" using dangling, reflective objects',
  'Set up a "kitty archaeological dig site" with hidden treats in a sand box',
  'Set up a "cat-sized ball pit" using a kiddie pool and plastic balls',
  'Design a "kitty codebreaker" puzzle with treats behind different mechanisms',
  'Make a "cat-friendly lava lamp" with floating objects in a sealed container',
  'Make a "cat-friendly rain stick" toy for auditory stimulation',
  'Make a "cat-friendly snow globe" with floating feathers or lightweight objects',
  'Set up a "feline fruit ninja" game with dangling, soft fruit-shaped toys',
  'Create a "kitty carnival wheel" for spinning and treat dispensing',
  'Design a "feline fidget spinner" toy for pawing and spinning',
  'Set up a "kitty card trick" game hiding treats under playing cards',
  'Create a "feline flip board" with reversible panels revealing toys or treats',
  'Design a "kitty domino rally" with cat-safe domino pieces',
  'Set up a "feline fibonacci spiral" climbing structure',
  'Create a "kitty curtain maze" using hanging fabric strips',
];
